title: Catalina
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#CACFD5'
    - '#866C53'
    - '#5F422D'
    - '#8C1D16'
    - '#CFA780'
  rhythmicContrast: 0
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: Catalina
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4495167
layout_spectrum: 0
